Tell user to run tgs-configure

diff --git a/build/package/deb/debian/postinst b/build/package/deb/debian/postinst
--- a/build/package/deb/debian/postinst
+++ b/build/package/deb/debian/postinst
@@ -1,7 +1,21 @@
-#!/bin/bash
+#!/bin/sh -e
 
-pushd /opt/tgstation-server
-dotnet /opt/tgstation-server/lib/Default/Tgstation.Server.Host.dll General:SetupWizardMode=Only
-popd
+if [[ "$1" = "configure" ]]; then
+	systemctl mask tgstation-server
+fi
 
 #DEBHELPER#
+
+if [[ "$1" = "configure" ]]; then
+	echo "  _            _        _   _                                                "
+	echo " | |_ __ _ ___| |_ __ _| |_(_) ___  _ __        ___  ___ _ ____   _____ _ __ "
+	echo " | __/ _` / __| __/ _` | __| |/ _ \| '_ \ _____/ __|/ _ \ '__\ \ / / _ \ '__|"
+	echo " | || (_| \__ \ || (_| | |_| | (_) | | | |_____\__ \  __/ |   \ V /  __/ |   "
+	echo "  \__\__, |___/\__\__,_|\__|_|\___/|_| |_|     |___/\___|_|    \_/ \___|_|   "
+	echo "     |___/                                                                   "
+	echo "tgstation-server is now installed but must first be configured"
+	echo "Run 'sudo tgs-configure' to interactively configure your server"
+	echo "Alternatively, edit '/etc/tgstation-server/appsettings.Production.yml' to your desired specifications"
+	echo "Once complete, run 'sudo systemctl start tgstation-server' to start the service"
+	echo "You should do this now to prevent the service from starting with invalid configuration on the next system reboot"
+fi
